name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image from Docker Hub
        run: sudo docker pull saswatdas123/new_patent_app
      - name: Delete Old Docker Container
        run: sudo docker rm -f new_patent_app-container || true
      - name: Run Docker Container 
        run: sudo docker run -it -d -p 8501:8501 --name new_patent_app-container saswatdas123/new_patent_app
