name: CD Pipeline


on:
   workflow_run:
     workflows: ["CI Pipeline"]
     types:
      - completed


jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Remove unnecessary files from the workspace...
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Pull Docker Image from Docker Hub
        run: sudo docker pull saswatdas123/new_patent_app2
      - name: Delete Old Docker Container
        run: sudo docker rm -f patent_app || true
      - name: Run Docker Container 
        run: sudo docker run -it -d -p 8501:8501 --name patent_app saswatdas123/new_patent_app2
